# Generated by Django 3.1.7 on 2021-06-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_person', models.CharField(max_length=20)),
                ('outbound_date', models.DateField(auto_now=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_manage.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_receipt', models.BinaryField()),
                ('specific_outbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='outbound_manage.outbound')),
            ],
        ),
    ]
