# Generated by Django 3.1.7 on 2021-05-08 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound_manage', '0001_initial'),
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_person', models.CharField(max_length=20)),
                ('outbound_date', models.DateField()),
                ('contract_number', models.CharField(max_length=50)),
                ('form_number', models.CharField(max_length=50)),
                ('quantity', models.SmallIntegerField()),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
                ('in_house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inbound_manage.inbound')),
                ('project_FK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_manage.project')),
            ],
            options={
                'ordering': ['outbound_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_receipt', models.BinaryField()),
                ('specific_outbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='outbound_manage.outbound')),
            ],
        ),
    ]
