# Generated by Django 3.1.7 on 2021-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbound',
            old_name='request_person',
            new_name='demand_person',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='in_house',
            new_name='inbound',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='project_FK',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='outbound',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='form_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='outbound_date',
            field=models.DateField(auto_now=True),
        ),
    ]
