# Generated by Django 3.1.7 on 2021-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='inbound_flag',
            field=models.BooleanField(choices=[(True, '已入库'), (False, '未入库')], default=False),
        ),
    ]
