# Generated by Django 3.1.7 on 2021-06-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0002_project_project_status'),
        ('purchase_manage', '0002_purchase_inbound_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_manage.project'),
        ),
    ]
