# Generated by Django 3.1.7 on 2021-06-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound_manage', '0004_auto_20210530_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=200)),
                ('status_code', models.SmallIntegerField(choices=[(0, '在库'), (1, '出库'), (2, '外借'), (3, '内借'), (4, '领用')], default=0)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inbound_manage.inbound')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
