# Generated by Django 3.1.7 on 2021-06-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound_manage', '0001_initial'),
        ('outbound_manage', '0001_initial'),
        ('reception_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=200, unique=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, '在库'), (1, '出库'), (2, '外借'), (3, '内借'), (4, '领用')], default=0)),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inbound_manage.inbound')),
                ('outbound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outbound_manage.outbound')),
                ('reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reception_manage.reception')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
