# Generated by Django 3.1.7 on 2021-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manage', '0002_auto_20210605_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='flag',
            field=models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True),
        ),
    ]
