# Generated by Django 3.1.7 on 2021-06-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_data', models.JSONField()),
                ('posterior_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LogSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_ip', models.CharField(max_length=30)),
                ('log_date', models.DateField()),
                ('operation_type', models.SmallIntegerField(choices=[(1, '登陆'), (2, '新增'), (3, '修改'), (4, '删除')])),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Log_related_consumer', to='consumer_manage.consumer')),
                ('log_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Details_of_operation', to='operation_log.logdetail')),
            ],
        ),
    ]
