# Generated by Django 3.1.7 on 2021-06-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer_manage', '0001_initial'),
        ('purchase_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_model', models.CharField(max_length=100, unique=True)),
                ('product_type', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_made_it', to='manufacturer_manage.manufacturer')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseProductRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('flag', models.BooleanField(choices=[(True, '已入库'), (False, '未入库')], default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_manage.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase_manage.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.ManyToManyField(through='product_manage.PurchaseProductRel', to='purchase_manage.Purchase'),
        ),
    ]
