# Generated by Django 3.1.7 on 2021-05-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproductrel',
            name='inbound',
        ),
    ]
