# Generated by Django 3.1.7 on 2021-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=10, unique=True)),
                ('password', models.CharField(default='b', max_length=100)),
                ('phone', models.BigIntegerField(default='f', unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('mail', models.EmailField(default='e', max_length=30, unique=True)),
                ('status', models.CharField(default='c', max_length=10)),
                ('type', models.CharField(default='w', max_length=10)),
                ('last_login_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
