# Generated by Django 3.1.7 on 2021-06-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_manage', '0004_auto_20210530_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='material_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
