# Generated by Django 3.1.7 on 2021-06-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_manage', '0005_auto_20210605_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='inbound_rel',
            new_name='pp_rel',
        ),
    ]
