# Generated by Django 3.1.7 on 2021-06-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_manage', '0006_auto_20210605_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbound',
            options={'ordering': ['id']},
        ),
    ]
