# Generated by Django 3.1.7 on 2021-06-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('project_code', models.CharField(max_length=30, unique=True)),
                ('project_status', models.SmallIntegerField(choices=[(0, '已立项'), (1, '已采购'), (2, '已入库'), (3, '已出库')], default=0)),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
            ],
            options={
                'ordering': ['project_code'],
            },
        ),
    ]
