# Generated by Django 3.1.7 on 2021-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.SmallIntegerField(choices=[(0, '已立项'), (1, '已采购'), (2, '已入库'), (3, '已出库')], default=0),
        ),
    ]
