# Generated by Django 3.1.7 on 2021-05-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('manufacturer_linkman', models.CharField(max_length=20)),
                ('manufacturer_contact', models.CharField(max_length=20)),
                ('cooperation_begin_date', models.DateField()),
                ('is_cooperated', models.BooleanField(choices=[(True, '合作中'), (False, '未合作')], default=True)),
                ('flag', models.BooleanField(choices=[(True, '未删除'), (False, '已删除')], default=True)),
            ],
            options={
                'ordering': ['is_cooperated'],
            },
        ),
    ]
